--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.1
-- Dumped by pg_dump version 9.3.1
-- Started on 2015-09-02 14:33:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 180 (class 3079 OID 11750)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2008 (class 0 OID 0)
-- Dependencies: 180
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 170 (class 1259 OID 32770)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2009 (class 0 OID 0)
-- Dependencies: 170
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 175 (class 1259 OID 32780)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id integer DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    accion character varying(20) NOT NULL,
    tabla character varying(64) NOT NULL,
    registro integer,
    observacion character varying(500)
);


ALTER TABLE public.bitacora OWNER TO postgres;

--
-- TOC entry 171 (class 1259 OID 32772)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2010 (class 0 OID 0)
-- Dependencies: 171
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 176 (class 1259 OID 32791)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id integer DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL,
    descripcion character varying(140)
);


ALTER TABLE public.credencial OWNER TO postgres;

--
-- TOC entry 172 (class 1259 OID 32774)
-- Name: dato_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE dato_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.dato_usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2011 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE dato_usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE dato_usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 177 (class 1259 OID 32799)
-- Name: dato_usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE dato_usuario (
    id integer DEFAULT nextval('dato_usuario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    usuario_id integer NOT NULL,
    cedula character varying(11) NOT NULL,
    nombre character varying(80) NOT NULL,
    apellido character varying(80) NOT NULL
);


ALTER TABLE public.dato_usuario OWNER TO postgres;

--
-- TOC entry 174 (class 1259 OID 32778)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2012 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 178 (class 1259 OID 32808)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id integer DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    usuario character varying(50) NOT NULL,
    password character varying(32) NOT NULL,
    estado boolean DEFAULT true NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 2013 (class 0 OID 0)
-- Dependencies: 178
-- Name: COLUMN usuario.estado; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.estado IS '1 = activado | 0 = inactivado';


--
-- TOC entry 173 (class 1259 OID 32776)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2014 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 179 (class 1259 OID 32820)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id integer DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    credencial_id integer NOT NULL
);


ALTER TABLE public.usuario_credencial OWNER TO postgres;

--
-- TOC entry 1997 (class 0 OID 32780)
-- Dependencies: 175
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2015 (class 0 OID 0)
-- Dependencies: 170
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 1, false);


--
-- TOC entry 1998 (class 0 OID 32791)
-- Dependencies: 176
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2016 (class 0 OID 0)
-- Dependencies: 171
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 1, false);


--
-- TOC entry 1999 (class 0 OID 32799)
-- Dependencies: 177
-- Data for Name: dato_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2017 (class 0 OID 0)
-- Dependencies: 172
-- Name: dato_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('dato_usuario_id_seq', 1, false);


--
-- TOC entry 2000 (class 0 OID 32808)
-- Dependencies: 178
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2001 (class 0 OID 32820)
-- Dependencies: 179
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2018 (class 0 OID 0)
-- Dependencies: 173
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, false);


--
-- TOC entry 2019 (class 0 OID 0)
-- Dependencies: 174
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 1, false);


--
-- TOC entry 1865 (class 2606 OID 32789)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 1867 (class 2606 OID 32798)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 1870 (class 2606 OID 32806)
-- Name: pkdato_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT pkdato_usuario PRIMARY KEY (id);


--
-- TOC entry 1872 (class 2606 OID 32816)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 1877 (class 2606 OID 32827)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 1863 (class 1259 OID 32790)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 1868 (class 1259 OID 32807)
-- Name: dato_usuario_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "dato_usuario_usuario_id_Idx" ON dato_usuario USING btree (usuario_id);


--
-- TOC entry 1878 (class 1259 OID 32828)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 1879 (class 1259 OID 32829)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 1880 (class 1259 OID 32830)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 1873 (class 1259 OID 32817)
-- Name: usuario_estado_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_estado_Idx" ON usuario USING btree (estado);


--
-- TOC entry 1874 (class 1259 OID 32818)
-- Name: usuario_usuario_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_usuario_Idx" ON usuario USING btree (usuario);


--
-- TOC entry 1875 (class 1259 OID 32819)
-- Name: usuario_usuario_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_usuario_password_Idx" ON usuario USING btree (usuario, password);


--
-- TOC entry 1881 (class 2606 OID 32831)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);


--
-- TOC entry 1882 (class 2606 OID 32836)
-- Name: fk_dato_usuario_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 1883 (class 2606 OID 32841)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id);


--
-- TOC entry 1884 (class 2606 OID 32846)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);


--
-- TOC entry 2007 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-09-02 14:33:11

--
-- PostgreSQL database dump complete
--

